export const CATEGORIES = [
  "Development",
  "Web Development",
  "Mobile Development",
  "AI & Machine Learning",
  "Data Science",
  "Cybersecurity",
  "Blockchain",
  "Game Development",
  "Business",
  "Finance & Accounting",
  "IT & Software",
  "Office Productivity",
  "Personal Development",
  "Design",
  "Marketing",
  "Lifestyle",
  "Health & Fitness",
  "Language",
  "Other",
] as const;
